/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,jsx}"],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				// Design System Colors - Atmospheric Precision
				surface: "#111319",
				"surface-dim": "#111319",
				"surface-bright": "#36393f",
				"surface-container-lowest": "#0b0e13",
				"surface-container-low": "#191c21",
				"surface-container": "#1d2025",
				"surface-container-high": "#272a30",
				"surface-container-highest": "#32353a",
				"on-surface": "#e1e2e9",
				"on-surface-variant": "#ccc7ae",
				"inverse-surface": "#e1e2e9",
				"inverse-on-surface": "#2e3036",
				outline: "#95917a",
				"outline-variant": "#4a4734",
				primary: "#ffffff",
				"on-primary": "#353100",
				"primary-container": "#f3e64b",
				"on-primary-container": "#6d6600",
				"inverse-primary": "#676000",
				"primary-fixed": "#f3e64b",
				"primary-fixed-dim": "#d6ca30",
				"on-primary-fixed": "#1f1c00",
				"on-primary-fixed-variant": "#4d4800",
				secondary: "#42efb4",
				"on-secondary": "#003827",
				"secondary-container": "#00d29a",
				"on-secondary-container": "#00543c",
				"secondary-fixed": "#56fdc2",
				"secondary-fixed-dim": "#2ae0a7",
				"on-secondary-fixed": "#002115",
				"on-secondary-fixed-variant": "#00513a",
				tertiary: "#ffffff",
				"on-tertiary": "#591c00",
				"tertiary-container": "#ffdbce",
				"on-tertiary-container": "#af4000",
				"tertiary-fixed": "#ffdbce",
				"tertiary-fixed-dim": "#ffb598",
				"on-tertiary-fixed": "#370e00",
				"on-tertiary-fixed-variant": "#7e2c00",
				error: "#ffb4ab",
				"on-error": "#690005",
				"error-container": "#93000a",
				"on-error-container": "#ffdad6",
				background: "#111319",
				"on-background": "#e1e2e9",
				"surface-variant": "#32353a",
			},
			fontFamily: {
				display: ["Sora", "sans-serif"],
				body: ["Sora", "sans-serif"],
				mono: ["JetBrains Mono", "monospace"],
				headline: ["Space Grotesk", "sans-serif"],
			},
			fontSize: {
				"display-lg": ["57px", { lineHeight: "64px", fontWeight: "700" }],
				"headline-md": ["32px", { lineHeight: "40px", fontWeight: "700" }],
				"headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
				"label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
				"label-sm": ["11px", { lineHeight: "16px", fontWeight: "500" }],
				"body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
				"body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
			},
			spacing: {
				"margin-mobile": "16px",
				"margin-desktop": "32px",
				gutter: "24px",
			},
			maxWidth: {
				"container-max": "1440px",
			},
			backgroundImage: {
				"aurora-yellow":
					"radial-gradient(circle, rgba(243, 230, 75, 0.15) 0%, transparent 70%)",
				"aurora-teal":
					"radial-gradient(circle, rgba(66, 239, 180, 0.15) 0%, transparent 70%)",
			},
			backdropBlur: {
				xl: "20px",
			},
			borderColor: {
				"surface-stroke": "rgba(255, 255, 255, 0.12)",
			},
			boxShadow: {
				glass: "0 8px 32px rgba(0, 0, 0, 0.3)",
			},
		},
	},
	plugins: [require("@tailwindcss/forms"), require("@tailwindcss/typography")],
};
